### ISSUE TITLE
Form namechange

### ISSUE THREAD

**Issue by thedrayman** [pwaldhauer/amazon-account-crawler#16]
`logged_in_page = page.form_with(:id => 'ap_signin_form') do |f|` is not working anymore.

Seem's Amazon changed the form name. I cangend this line to: 
`logged_in_page = page.form_with(:name => 'signIn') do |f|` 

This is working at the moment.

**Comment by pwaldhauer** [comment]
Could you create a pull request please? This would be much appreciated!

**Comment by thedrayman** [comment]
Pull request done! Thanks!
